title:              코끼리와 딩가딩가[코딩]
email:              hyebin218@naver.com
description:        매일 매일 코딩하는 블로그
author:             yoohyebin
baseurl:            ""
url:                "https://github.com/yoohyebin/yoohyebin.github.io.git"

# Social Profiles
twitter_username:   
github_username:    yoohyebin
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site